// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DIRECT_URL"),
    shadowDatabaseUrl: undefined,
    // shadowDatabaseUrl: env("DATABASE_URL"),
    // TODO: 수정! 마이그레이션 불가. (이유 다시 정리해봐야함. prisma v7 출시된지 한달되어서 자료 못찾겠음. 아마 버그일듯. 버전업 주시)
  },
});
